-- explore all countries customers are from
SELECT DISTINCT country 
FROM gold.dim_customers

-- explore all categories from products
SELECT DISTINCT category, subcategory, product_name 
FROM gold.dim_products
ORDER BY category, subcategory, product_name

-- find date of the first and last order
SELECT 
    MIN(order_date) AS first_order ,
    MAX(order_date) AS last_order,
    DATEDIFF(YEAR, MIN(order_date), MAX(order_date)) AS year_range
FROM gold.fact_sales

-- find youngest and oldest customer
SELECT
    MIN(birthdate) AS oldest_birthdate,
    DATEDIFF(YEAR, MIN(birthdate), GETDATE()) AS oldest_year,
    MAX(birthdate) AS youngest,
    DATEDIFF(YEAR, MAX(birthdate), GETDATE()) AS youngest_year
FROM gold.dim_customers

-- find the total sales
SELECT SUM(sales_amount) AS total_sales
FROM gold.fact_sales

-- find how many items are sold
SELECT SUM(quantity) AS total_quantity
FROM gold.fact_sales

-- find the average selling price
SELECT AVG(price) AS avg_price
FROM gold.fact_sales

-- find the total number of orders
SELECT COUNT(order_number) AS total_orders
FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales

--find the total number of products
SELECT COUNT(product_name) AS total_products
FROM gold.dim_products
SELECT COUNT(DISTINCT product_name) AS total_products
FROM gold.dim_products

-- find the total number of customers
SELECT COUNT(customer_key) AS total_customers
FROM gold.dim_customers

-- find the total number of customers that have placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers
FROM gold.fact_sales

-- report that shows all metrics
SELECT 
    'Total Sales' AS measure_name,
    SUM(sales_amount) AS measure_value
FROM gold.fact_sales
UNION ALL
SELECT 
    'Total Quantity' AS measure_name,
    SUM(quantity) AS measure_value
FROM gold.fact_sales
UNION ALL
SELECT 
    'Average Price' AS measure_name,
    AVG(price) AS measure_value
FROM gold.fact_sales
UNION ALL
SELECT
    'Total orders duplicated' AS measure_name,
    COUNT(order_number) AS measure_value
FROM gold.fact_sales
UNION ALL
SELECT 
    'Total orders' AS measure_name,
    COUNT(DISTINCT order_number) AS measure_value
FROM gold.fact_sales
UNION ALL
SELECT 
    'Count of Customers' AS measure_name,
    COUNT(customer_key) AS measure_value
FROM gold.dim_customers
UNION ALL
SELECT 
    'Count of Customers who Ordered' AS measure_name,
    COUNT(DISTINCT customer_key) AS measure_value
FROM gold.fact_sales

-- find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- find the total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- find the average cost in each category
SELECT
    category,
    AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC

-- find the total revenue generated by each category
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- find the total revenue generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC

-- find the distribution of sold items across countries
SELECT
    c.country,
    SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY
    c.country
ORDER BY total_items_sold DESC

-- which 5 products generate the highest revenue
SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

-- what are the 5 worst performing products in terms of sales
SELECT * FROM (
    SELECT
        p.product_name,
        SUM(f.sales_amount) AS total_revenue,
        RANK() OVER(ORDER BY SUM(f.sales_amount) ASC) AS product_rank
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_products AS p
    ON f.product_key = p.product_key
    GROUP BY p.product_name
) AS t
WHERE product_rank <= 5

-- find the top 10 customers who have generated the highest revenue
SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC

-- find the top 3 customers with the fewest orders placed
SELECT TOP 3
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_orders ASC
